### ISSUE TITLE
failed to load command

### ISSUE THREAD

**Issue by samcro1967** [davidkus/triviacrack-client#2]
BOT seems to be encounter periodic issues where commands fail and container exits.

**Log File**
Waiting 4 seconds before the next question...

 Category : science
 Question : When does a caterpillar turn into a liquid?
   Answer : In the pupa - Correct!

Waiting 4 seconds before the next question...
UncaughtThrowError: uncaught throw #<TriviaCrack::Errors::RequestError: Request to the Trivia Crack API failed.>
  bin/trivia-crack:50:in `throw'
  bin/trivia-crack:50:in `rescue in start_bot'
  bin/trivia-crack:37:in `start_bot'
  bin/trivia-crack:21:in `bot'
  /usr/local/bundle/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/local/bundle/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'

 Category : geography
 Question : Which California city was previously known as Yerba Buena?
   Answer : San Francisco - Correct!

Waiting 3 seconds before the next question...

 Category : arts
 Question : Where were violins invented?
   Answer : Italy - Correct!
Finished playing game 7450301666. Status: pending_approval.
Playing game 7446527403 against 555ambw.

Waiting 3 seconds before the next question...

 Category : history
 Question : What year did the first cell phone come out?
   Answer : 1973bundler: failed to load command: bin/trivia-crack (bin/trivia-crack)
  /usr/local/bundle/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  bin/trivia-crack:57:in `<top (required)>'

**Comment by davidkus** [comment]
Just pushed an update to improve logging, as I can't really tell what went wrong looking at these logs.

Try running with those code changes and re-open this if/when you encounter the error again.

**Comment by samcro1967** [comment]
Contains a bot more info:

Starting to play Trivia Crack as b33r1sg00d.
Fetching games for b33r1sg00d...
Playing game 7507044593 against fractalhelix.
bundler: failed to load command: bin/trivia-crack (bin/trivia-crack)
UncaughtThrowError: uncaught throw #<ArgumentError: invalid argument - 30..20>
  bin/trivia-crack:50:in `throw'
  bin/trivia-crack:50:in `rescue in start_bot'
  bin/trivia-crack:37:in `start_bot'
  bin/trivia-crack:21:in `bot'
  /usr/local/bundle/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/local/bundle/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
  /usr/local/bundle/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  bin/trivia-crack:57:in `<top (required)>'
