### ISSUE TITLE
bundler: failed to load command: bin/trivia-crack (bin/trivia-crack)

### ISSUE THREAD

**Issue by samcro1967** [davidkus/triviacrack-client#3]
Opening a new thread with the more detailed loggin information.

Starting to play Trivia Crack as b33r1sg00d.
Fetching games for b33r1sg00d...
Playing game 7507044593 against fractalhelix.
bundler: failed to load command: bin/trivia-crack (bin/trivia-crack)
UncaughtThrowError: uncaught throw #<ArgumentError: invalid argument - 30..20>
bin/trivia-crack:50:in throw' bin/trivia-crack:50:in rescue in start_bot'
bin/trivia-crack:37:in start_bot' bin/trivia-crack:21:in bot'
/usr/local/bundle/gems/thor-0.19.4/lib/thor/command.rb:27:in run' /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:126:in invoke_command'
/usr/local/bundle/gems/thor-0.19.4/lib/thor.rb:369:in dispatch' /usr/local/bundle/gems/thor-0.19.4/lib/thor/base.rb:444:in start'
bin/trivia-crack:57:in `<top (required)>'

**Comment by davidkus** [comment]
Hmm...

I'm wondering if you've modified either of these lines:
https://github.com/davidkus/triviacrack-client/blob/5408481ed89063a3c993a585c8c71cf8c34d74a7/lib/triviacrack/client/bot.rb#L61
https://github.com/davidkus/triviacrack-client/blob/5408481ed89063a3c993a585c8c71cf8c34d74a7/lib/triviacrack/client/bot.rb#L64

I believe the exception is being thrown here:
https://github.com/davidkus/triviacrack-client/blob/5408481ed89063a3c993a585c8c71cf8c34d74a7/lib/triviacrack/client/bot.rb#L82

**Comment by samcro1967** [comment]
I downloaded the most recent code just now and tried to build it.  The image fails to build and I get the following error:

C:\Users\user\Documents\Docker\triviacrack-client>docker build -t triviacrack .
Sending build context to Docker daemon  49.66kB
Step 1/5 : FROM ruby:2.6.5
 ---> dcb28425fa35
Step 2/5 : WORKDIR /code
 ---> Running in bf7a477d40a3
Removing intermediate container bf7a477d40a3
 ---> 289201e63fbb
Step 3/5 : ADD . /code
 ---> 6064160d2b05
Step 4/5 : RUN bundle install
 ---> Running in 5c752180f27b
/usr/local/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.1.4) required by your /code/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.1.4`
        from /usr/local/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
        from /usr/local/bin/bundle:23:in `<main>'
The command '/bin/sh -c bundle install' returned a non-zero code: 1

**Comment by davidkus** [comment]
Just pushed a fix to the Dockerfile, it should build properly now.

**Comment by samcro1967** [comment]
Builds properly now and seems to be working.
